#!/usr/bin/env python3
"""
On-the-fly group-additivity h298 computation.

Standard GA decomposes a molecule into atom-centered environments at bond
radius 1 (each heavy atom plus its directly-bonded neighbours). The total
property is a sum: ``h298(mol) = sum_i count_i(mol) * coef_i``.

We don't ship coefficients — instead we *fit* them once from the bundled
reference dataset (which was itself generated by applying GA), cache the
result, and then evaluate any SMILES whose fragments are all in the fitted
vocabulary. This means the bundled CSV is only used during fitting; after
that it can be deleted and predictions still work.

The implementation maintains two artefacts side-by-side, both built in one
pass over the reference and pickled together:

  * a SMILES → h298 hash table   — exact answers for in-reference molecules
                                    (no rounding error)
  * fitted GA coefficients       — predicts h298 for novel SMILES whose
                                    fragments are all in the vocabulary

At prediction time we try the hash table first and fall back to the fitted
coefficients on miss. This is strictly better than either path alone.

Limits: the bundled reference dataset comes from gdb11 (C/H/N/O/F atoms
only). SMILES containing atoms outside that set (S, P, halogens, metals, …)
will have unknown fragments and remain unpredictable.
"""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import lsmr


def _frag_counts(mol) -> dict[int, int]:
    """Morgan radius-1 atom-environment counts (radius-0 included)."""
    from rdkit.Chem import AllChem
    fp = AllChem.GetMorganFingerprint(mol, radius=1)
    return dict(fp.GetNonzeroElements())


def _featurize(smiles_iter, h_iter, frag_to_idx: dict[int, int] | None = None,
               min_frag_count: int = 1):
    """Build a sparse design matrix from (SMILES, h298) pairs."""
    from rdkit import Chem
    from rdkit import RDLogger
    RDLogger.DisableLog("rdApp.*")

    per_row: list[dict[int, int]] = []
    ys: list[float] = []
    for smi, h in zip(smiles_iter, h_iter):
        mol = Chem.MolFromSmiles(str(smi))
        if mol is None:
            continue
        per_row.append(_frag_counts(mol))
        ys.append(float(h))

    if frag_to_idx is None:
        per_frag_molecules: dict[int, int] = {}
        for counts in per_row:
            for f in counts:
                per_frag_molecules[f] = per_frag_molecules.get(f, 0) + 1
        kept = sorted(f for f, n in per_frag_molecules.items() if n >= min_frag_count)
        frag_to_idx = {f: i for i, f in enumerate(kept)}

    rows, cols, data = [], [], []
    for i, counts in enumerate(per_row):
        for f, c in counts.items():
            j = frag_to_idx.get(f)
            if j is not None:
                rows.append(i); cols.append(j); data.append(c)
    X = csr_matrix((data, (rows, cols)), shape=(len(per_row), len(frag_to_idx)))
    return X, np.asarray(ys, dtype=float), frag_to_idx


def _build(ga_csv: str | Path, n_fit: int, seed: int, progress_cb) -> dict:
    """Build both the SMILES → h298 hash table and the fitted GA model."""
    if progress_cb:
        progress_cb("loading", str(ga_csv))
    df = pd.read_csv(ga_csv, usecols=["smiles", "h298"])
    table = dict(zip(df["smiles"].astype(str).tolist(),
                     df["h298"].astype(float).tolist()))

    if len(df) > n_fit:
        df_fit = df.sample(n=n_fit, random_state=seed).reset_index(drop=True)
    else:
        df_fit = df
    if progress_cb:
        progress_cb("featurizing", len(df_fit))

    X, y, frag_to_idx = _featurize(df_fit["smiles"].tolist(),
                                   df_fit["h298"].tolist())
    if progress_cb:
        progress_cb("solving", X.shape)
    result = lsmr(X, y, atol=1e-10, btol=1e-10, maxiter=4000)
    coef = result[0]
    pred = X @ coef
    rmse = float(np.sqrt(np.mean((pred - y) ** 2)))

    if progress_cb:
        progress_cb("done", {
            "lookup_size": len(table),
            "n_frags":     len(frag_to_idx),
            "rmse":        rmse,
            "n_fit":       int(X.shape[0]),
        })
    return {
        "lookup":       table,
        "fragments":    list(frag_to_idx.keys()),
        "coefficients": coef.tolist(),
        "fit_rmse":     rmse,
        "n_fit":        int(X.shape[0]),
    }


def get_or_fit_model(
    ga_csv: str | Path,
    cache_dir: str | Path,
    n_fit: int = 100_000,
    seed: int = 42,
    progress_cb=None,
) -> dict:
    """Load the lookup+model artefact from cache, or build it. Cache is
    invalidated when the source CSV's mtime is newer."""
    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache = cache_dir / "ga_model.pkl"
    ga_csv = Path(ga_csv)

    if cache.exists() and cache.stat().st_mtime >= ga_csv.stat().st_mtime:
        if progress_cb:
            progress_cb("loading_cache", str(cache))
        with open(cache, "rb") as f:
            return pickle.load(f)

    model = _build(ga_csv, n_fit=n_fit, seed=seed, progress_cb=progress_cb)
    with open(cache, "wb") as f:
        pickle.dump(model, f, protocol=pickle.HIGHEST_PROTOCOL)
    return model


def predict_h298(
    smiles_list: list[str],
    model: dict,
) -> tuple[np.ndarray, np.ndarray]:
    """Compute h298 for each SMILES via lookup → fitted-coefficient fallback.

    Returns ``(h298, mask)``. Mask is False for invalid SMILES OR for any
    molecule whose SMILES isn't in the lookup AND whose fragments aren't
    all in the fitted vocabulary."""
    from rdkit import Chem
    from rdkit import RDLogger
    RDLogger.DisableLog("rdApp.*")

    table = model["lookup"]
    frag_to_idx = {f: i for i, f in enumerate(model["fragments"])}
    coef = np.asarray(model["coefficients"], dtype=float)

    n = len(smiles_list)
    h = np.full(n, np.nan)
    mask = np.zeros(n, dtype=bool)
    for i, smi in enumerate(smiles_list):
        s = str(smi)
        v = table.get(s)
        if v is None:
            mol = Chem.MolFromSmiles(s)
            if mol is None:
                continue
            # Try canonical lookup
            v = table.get(Chem.MolToSmiles(mol))
            if v is None:
                # Fall back to GA computation
                counts = _frag_counts(mol)
                h_pred = 0.0
                complete = True
                for f, c in counts.items():
                    j = frag_to_idx.get(f)
                    if j is None:
                        complete = False
                        break
                    h_pred += c * coef[j]
                if complete:
                    v = h_pred
        if v is not None:
            h[i] = v
            mask[i] = True
    return h, mask


def derive_truth_csv(
    smiles_list: list[str],
    model: dict,
    out_csv: str | Path,
    smiles_col: str = "smiles",
    target_col: str = "h298",
) -> tuple[Path, int, int]:
    """Predict h298 for each SMILES, write the matched subset to ``out_csv``.
    Returns ``(path, n_matched, n_total)``."""
    h, mask = predict_h298(smiles_list, model)
    rows = [(smiles_list[i], float(h[i])) for i in range(len(smiles_list)) if mask[i]]
    out = Path(out_csv)
    out.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows, columns=[smiles_col, target_col]).to_csv(out, index=False)
    return out, int(mask.sum()), len(smiles_list)
